@Web_API_project_HostAddress = http://localhost:5153

GET {{Web_API_project_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{Web_API_project_HostAddress}}/pizza/
Accept: application/json

###

GET {{Web_API_project_HostAddress}}/pizza/3
Accept: application/json

###

POST {{Web_API_project_HostAddress}}/pizza/
Content-Type: application/json

{
    "name" : "Hawaii",
    "isGlutenFree" : false
}

###

PUT {{Web_API_project_HostAddress}}/pizza/3
Content-Type: application/json

{
     "id": 3,
    "name": "Hawaiian",
    "isGlutenFree": false
}

###

DELETE {{Web_API_project_HostAddress}}/pizza/3
Content-Type: application/json

###